version: '3.8'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile_frontend
    container_name: sample_frontend
    volumes:
      - "./frontend:/workspace"
    ports:
      - "3000:3000"
    tty: true
    command: sh -c "npm run dev"
